# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page1.ui'
#
# Created: Wed Oct  9 09:10:02 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Page1(object):
    def setupUi(self, Page1):
        Page1.setObjectName(_fromUtf8("Page1"))
        Page1.resize(400, 300)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Page1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(Page1)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.gridLayout = QtGui.QGridLayout(self.tab1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lbMethod = QtGui.QLabel(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbMethod.sizePolicy().hasHeightForWidth())
        self.lbMethod.setSizePolicy(sizePolicy)
        self.lbMethod.setScaledContents(False)
        self.lbMethod.setWordWrap(True)
        self.lbMethod.setObjectName(_fromUtf8("lbMethod"))
        self.horizontalLayout.addWidget(self.lbMethod)
        self.cmbMethod = QtGui.QComboBox(self.tab1)
        self.cmbMethod.setModelColumn(0)
        self.cmbMethod.setObjectName(_fromUtf8("cmbMethod"))
        self.cmbMethod.addItem(_fromUtf8(""))
        self.cmbMethod.addItem(_fromUtf8(""))
        self.cmbMethod.addItem(_fromUtf8(""))
        self.cmbMethod.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cmbMethod)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkCoastline = QtGui.QCheckBox(self.tab2)
        self.checkCoastline.setObjectName(_fromUtf8("checkCoastline"))
        self.horizontalLayout_3.addWidget(self.checkCoastline)
        self.cmbCoastline = QtGui.QComboBox(self.tab2)
        self.cmbCoastline.setEnabled(False)
        self.cmbCoastline.setObjectName(_fromUtf8("cmbCoastline"))
        self.cmbCoastline.addItem(_fromUtf8(""))
        self.cmbCoastline.addItem(_fromUtf8(""))
        self.cmbCoastline.addItem(_fromUtf8(""))
        self.cmbCoastline.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cmbCoastline)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.checkBathymetry = QtGui.QCheckBox(self.tab2)
        self.checkBathymetry.setObjectName(_fromUtf8("checkBathymetry"))
        self.horizontalLayout_4.addWidget(self.checkBathymetry)
        self.cmbBathymetry = QtGui.QComboBox(self.tab2)
        self.cmbBathymetry.setEnabled(False)
        self.cmbBathymetry.setObjectName(_fromUtf8("cmbBathymetry"))
        self.cmbBathymetry.addItem(_fromUtf8(""))
        self.cmbBathymetry.addItem(_fromUtf8(""))
        self.cmbBathymetry.addItem(_fromUtf8(""))
        self.cmbBathymetry.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.cmbBathymetry)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.checkLandingSites = QtGui.QCheckBox(self.tab2)
        self.checkLandingSites.setObjectName(_fromUtf8("checkLandingSites"))
        self.horizontalLayout_5.addWidget(self.checkLandingSites)
        self.cmbLandingSites = QtGui.QComboBox(self.tab2)
        self.cmbLandingSites.setEnabled(False)
        self.cmbLandingSites.setObjectName(_fromUtf8("cmbLandingSites"))
        self.cmbLandingSites.addItem(_fromUtf8(""))
        self.cmbLandingSites.addItem(_fromUtf8(""))
        self.cmbLandingSites.addItem(_fromUtf8(""))
        self.cmbLandingSites.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.cmbLandingSites)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.CheckMaritime = QtGui.QCheckBox(self.tab2)
        self.CheckMaritime.setObjectName(_fromUtf8("CheckMaritime"))
        self.horizontalLayout_6.addWidget(self.CheckMaritime)
        self.cmbMaritime = QtGui.QComboBox(self.tab2)
        self.cmbMaritime.setEnabled(False)
        self.cmbMaritime.setObjectName(_fromUtf8("cmbMaritime"))
        self.cmbMaritime.addItem(_fromUtf8(""))
        self.cmbMaritime.addItem(_fromUtf8(""))
        self.cmbMaritime.addItem(_fromUtf8(""))
        self.cmbMaritime.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.cmbMaritime)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.checkOther = QtGui.QCheckBox(self.tab2)
        self.checkOther.setObjectName(_fromUtf8("checkOther"))
        self.horizontalLayout_7.addWidget(self.checkOther)
        self.cmbOther = QtGui.QComboBox(self.tab2)
        self.cmbOther.setEnabled(False)
        self.cmbOther.setObjectName(_fromUtf8("cmbOther"))
        self.cmbOther.addItem(_fromUtf8(""))
        self.cmbOther.addItem(_fromUtf8(""))
        self.cmbOther.addItem(_fromUtf8(""))
        self.cmbOther.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.cmbOther)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.tab11 = QtGui.QWidget()
        self.tab11.setObjectName(_fromUtf8("tab11"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab11)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lbMethod2 = QtGui.QLabel(self.tab11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbMethod2.sizePolicy().hasHeightForWidth())
        self.lbMethod2.setSizePolicy(sizePolicy)
        self.lbMethod2.setScaledContents(False)
        self.lbMethod2.setWordWrap(True)
        self.lbMethod2.setObjectName(_fromUtf8("lbMethod2"))
        self.horizontalLayout_8.addWidget(self.lbMethod2)
        self.cmbMethod2 = QtGui.QComboBox(self.tab11)
        self.cmbMethod2.setObjectName(_fromUtf8("cmbMethod2"))
        self.cmbMethod2.addItem(_fromUtf8(""))
        self.cmbMethod2.addItem(_fromUtf8(""))
        self.cmbMethod2.addItem(_fromUtf8(""))
        self.cmbMethod2.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.cmbMethod2)
        self.tabWidget.addTab(self.tab11, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.checkComplete = QtGui.QCheckBox(Page1)
        self.checkComplete.setObjectName(_fromUtf8("checkComplete"))
        self.verticalLayout_2.addWidget(self.checkComplete)
        self.lbMethod.setBuddy(self.cmbMethod)
        self.lbMethod2.setBuddy(self.cmbMethod)

        self.retranslateUi(Page1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.checkCoastline, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbCoastline.setEnabled)
        QtCore.QObject.connect(self.checkBathymetry, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbBathymetry.setEnabled)
        QtCore.QObject.connect(self.checkLandingSites, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbLandingSites.setEnabled)
        QtCore.QObject.connect(self.CheckMaritime, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbMaritime.setEnabled)
        QtCore.QObject.connect(self.checkOther, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cmbOther.setEnabled)
        QtCore.QObject.connect(self.cmbMethod, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Page1.triggerMethod)
        QtCore.QMetaObject.connectSlotsByName(Page1)

    def retranslateUi(self, Page1):
        Page1.setWindowTitle(QtGui.QApplication.translate("Page1", "WizardPage", None, QtGui.QApplication.UnicodeUTF8))
        Page1.setTitle(QtGui.QApplication.translate("Page1", "Initial Project Planning Step", None, QtGui.QApplication.UnicodeUTF8))
        self.lbMethod.setText(QtGui.QApplication.translate("Page1", "&Select a Method", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMethod.setItemText(0, QtGui.QApplication.translate("Page1", "Please Choose one...", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMethod.setItemText(1, QtGui.QApplication.translate("Page1", "Free-hand interactive", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMethod.setItemText(2, QtGui.QApplication.translate("Page1", "From list of countries/regions", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMethod.setItemText(3, QtGui.QApplication.translate("Page1", "From list of water areas", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), QtGui.QApplication.translate("Page1", "Broad Definition of AoI", None, QtGui.QApplication.UnicodeUTF8))
        self.checkCoastline.setText(QtGui.QApplication.translate("Page1", "Coastline", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbCoastline.setItemText(0, QtGui.QApplication.translate("Page1", "Please choose one...", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbCoastline.setItemText(1, QtGui.QApplication.translate("Page1", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbCoastline.setItemText(2, QtGui.QApplication.translate("Page1", "Digitize", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbCoastline.setItemText(3, QtGui.QApplication.translate("Page1", "Get from plugin/web repositories", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBathymetry.setText(QtGui.QApplication.translate("Page1", "Bathymetry", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbBathymetry.setItemText(0, QtGui.QApplication.translate("Page1", "Please choose one...", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbBathymetry.setItemText(1, QtGui.QApplication.translate("Page1", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbBathymetry.setItemText(2, QtGui.QApplication.translate("Page1", "Digitize", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbBathymetry.setItemText(3, QtGui.QApplication.translate("Page1", "Get from plugin/web repositories", None, QtGui.QApplication.UnicodeUTF8))
        self.checkLandingSites.setText(QtGui.QApplication.translate("Page1", "Landing Sites", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbLandingSites.setItemText(0, QtGui.QApplication.translate("Page1", "Please choose one...", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbLandingSites.setItemText(1, QtGui.QApplication.translate("Page1", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbLandingSites.setItemText(2, QtGui.QApplication.translate("Page1", "Digitize", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbLandingSites.setItemText(3, QtGui.QApplication.translate("Page1", "Get from plugin/web repositories", None, QtGui.QApplication.UnicodeUTF8))
        self.CheckMaritime.setText(QtGui.QApplication.translate("Page1", "Maritime Boundaries", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMaritime.setItemText(0, QtGui.QApplication.translate("Page1", "Please choose one...", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMaritime.setItemText(1, QtGui.QApplication.translate("Page1", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMaritime.setItemText(2, QtGui.QApplication.translate("Page1", "Digitize", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMaritime.setItemText(3, QtGui.QApplication.translate("Page1", "Get from plugin/web repositories", None, QtGui.QApplication.UnicodeUTF8))
        self.checkOther.setText(QtGui.QApplication.translate("Page1", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOther.setItemText(0, QtGui.QApplication.translate("Page1", "Please choose one...", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOther.setItemText(1, QtGui.QApplication.translate("Page1", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOther.setItemText(2, QtGui.QApplication.translate("Page1", "Digitize", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOther.setItemText(3, QtGui.QApplication.translate("Page1", "Get from plugin/web repositories", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), QtGui.QApplication.translate("Page1", "Compilation of Base Data", None, QtGui.QApplication.UnicodeUTF8))
        self.lbMethod2.setText(QtGui.QApplication.translate("Page1", "&Select a Method", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMethod2.setItemText(0, QtGui.QApplication.translate("Page1", "Please choose one...", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMethod2.setItemText(1, QtGui.QApplication.translate("Page1", "Free-hand interactive", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMethod2.setItemText(2, QtGui.QApplication.translate("Page1", "From list of countries/regions", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMethod2.setItemText(3, QtGui.QApplication.translate("Page1", "From list of water areas", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab11), QtGui.QApplication.translate("Page1", "Refine the AoI", None, QtGui.QApplication.UnicodeUTF8))
        self.checkComplete.setText(QtGui.QApplication.translate("Page1", "Complete", None, QtGui.QApplication.UnicodeUTF8))

